name: DocBox
on:
  push:
    branches:
      - master
      - main
    # Only run if *.cfc files are modified
    paths:
      - '**.cfc'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: Ortus-Solutions/commandbox-action@v1
        with:
          cmd: docbox generate strategy=HTML mapping=DocBox excludes=test|ModuleConfig strategy-outputDir=docs strategy-projectTitle=DocBox

      - name: Commit Docs Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "📖 DOC: Auto-generate DocBox API docs"