name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - development

jobs:
  # UPDATE TO THE MODULE REPO SO PR'S CAN REUSE IT
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  # Check format
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format:check
